# Generated by Django 4.0.3 on 2022-03-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_alter_note_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='users',
        ),
    ]
