# Generated by Django 4.0.3 on 2022-03-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0010_alter_note_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='users',
            new_name='note_user',
        ),
    ]
